version: '3.8'
services:
  sync:
    build:
      context: syncing-server
      dockerfile: ./syncing-server/Dockerfile
      args:
        optimize_for_raspberry_pi: "true"
  db:
    image: tobi312/rpi-mariadb
